public class TestED248 {
    public static void main(String[] args) {
        int n = 1000;
        IntSet s1 = new BooleanArrayIntSet(n);
        IntSet s2 = new BooleanArrayIntSet(n);
        IntSet s3 = new BooleanArrayIntSet(n);
        IntSet s4 = new BooleanArrayIntSet(n);
        IntSet s5 = new BooleanArrayIntSet(n);
        IntSet s6 = new BooleanArrayIntSet(n);
        IntSet s7 = new BooleanArrayIntSet(n);

        System.out.println("s1.size = " + s1.size());
        System.out.println("s1.add(42) = " + s1.add(42));
        System.out.println("s1.size = " + s1.size());
        System.out.println("s1.add(42) = " + s1.add(42));
        System.out.println("s1.add(21) = " + s1.add(21));
        System.out.println("s1.add(10) = " + s1.add(10));
        System.out.println("s1.size = " + s1.size());
        System.out.println("s1.contains(10) = " + s1.contains(10));
        System.out.println("s1.contains(21) = " + s1.contains(21));
        System.out.println("s1.contains(42) = " + s1.contains(42));
        System.out.println("s1.contains(9) = " + s1.contains(9));
        System.out.println("s1.remove(42) = " + s1.remove(42));
        System.out.println("s1.size() = " + s1.size());
        System.out.println("s1.contains(10) = " + s1.contains(10));
        System.out.println("s1.contains(21) = " + s1.contains(21));
        System.out.println("s1.contains(42) = " + s1.contains(42));
        System.out.println("s1.remove(21) = " + s1.remove(21));
        System.out.println("s1.remove(21) = " + s1.remove(21));
        System.out.println("s1.size() = " + s1.size());
        System.out.println("s1.contains(10) = " + s1.contains(10));
        System.out.println("s1.contains(21) = " + s1.contains(21));
        System.out.println("s1.contains(42) = " + s1.contains(42));
        System.out.println("s1.remove(10) = " + s1.remove(10));
        System.out.println("s1.remove(10) = " + s1.remove(10));
        System.out.println("s1.size() = " + s1.size());
        System.out.println("s1.contains(10) = " + s1.contains(10));
        System.out.println("s1.contains(21) = " + s1.contains(21));
        System.out.println("s1.contains(42) = " + s1.contains(42));
        System.out.println("s1.add(1) = " + s1.add(1));
        System.out.println("s1.add(2) = " + s1.add(2));
        s1.clear();
        System.out.println("s1.clear() = " + s1);
        System.out.println("s1.contains(1) = " + s1.contains(1));
        System.out.println("s1.contains(2) = " + s1.contains(2));
        System.out.println("s1.size() = " + s1.size());
        System.out.println("s1.equals(s2) = " + s1.equals(s2));
        System.out.println("s1.add(1000) = " + s1.add(1000));
        System.out.println("s1.equals(s2) = " + s1.equals(s2));
        System.out.println("s2.add(1000) = " + s2.add(1000));
        System.out.println("s1.equals(s2) = " + s1.equals(s2));
        System.out.println("s1.add(500) = " + s1.add(500));
        System.out.println("s2.equals(s1) = " + s2.equals(s1));
        System.out.println("s2.add(500) = " + s2.add(500));
        System.out.println("s2.equals(s1) = " + s2.equals(s1));
        s3 = s1.intersection(s2);
        System.out.println("s3.intersection(s1,s2) = " + s1.intersection(s2));
        System.out.println("s3.equals(s1) = " + s3.equals(s1));
        System.out.println("s3.equals(s2) = " + s3.equals(s2));
        System.out.println("s4.add(11) = " + s4.add(11));
        System.out.println("s4.add(12) = " + s4.add(12));
        System.out.println("s4.add(13) = " + s4.add(13));
        System.out.println("s4.add(14) = " + s4.add(14));
        System.out.println("s4.add(15) = " + s4.add(15));
        System.out.println("s4.add(16) = " + s4.add(16));
        System.out.println("s4.add(17) = " + s4.add(17));
        System.out.println("s5.add(11) = " + s5.add(11));
        System.out.println("s5.add(2) = " + s5.add(2));
        System.out.println("s5.add(13) = " + s5.add(13));
        System.out.println("s5.add(4) = " + s5.add(4));
        System.out.println("s5.add(15) = " + s5.add(15));
        System.out.println("s5.add(6) = " + s5.add(6));
        System.out.println("s5.add(17) = " + s5.add(17));
        s6 = s4.intersection(s5);
        System.out.println("s6 = s4.intersection(s5) = " + s4.intersection(s5));
        System.out.println("s6.size() = " + s6.size());
        s5.clear();
        System.out.println("s5.clear() = " + s5);
        s6 = s4.intersection(s5);
        System.out.println("s6 = s4.intersection(s5) = " + s4.intersection(s5));
        System.out.println("s6.size() = " + s6.size());
        s7 = s6.intersection(s4);
        System.out.println("s7 = s6.intersection(s4) = " + s6.intersection(s4));
        System.out.println("s7.size() = " + s7.size());

    }
}